services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - app-db
      - hangfire-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppDatabase=Host=app-db;Database=data_transform;Username=postgres;Password=postgres;
      - ConnectionStrings__HangfireDatabase=Host=hangfire-db;Database=hangfire;Username=postgres;Password=postgres;

  app-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data_transform
    ports:
      - "5432:5432"
    volumes:
      - app-data:/var/lib/postgresql/data

  hangfire-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hangfire
    ports:
      - "5433:5432"
    volumes:
      - hangfire-data:/var/lib/postgresql/data

volumes:
  app-data:
  hangfire-data: